### ISSUE TITLE
Test that minimalkv works

### ISSUE THREAD

**Issue by jtilly** [conda-forge/minimalkv-feedstock#16]
### Comment:

Can we add a test to the recipe that detects breakage such as we had with version 1.4.0?

A test could look like this:

```
test:
  - imports:
    - minimalkv
  commands:
    - pip check
    - python -c 'from minimalkv import get_store; get_store("fs", path=".")'
    - python -c 'from minimalkv import get_store; get_store("hfs", path=".")'
  requires:
    - pip
    - fsspec
```

However, this would mean we wouldn't test if `import minimalkv` works when `fsspec` is _not_ installed. Is there a way to have two separate tests in a recipe?
